# Generated by Django 6.0.1 on 2026-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='processing', max_length=30),
        ),
    ]

