# Generated by Django 5.2.10 on 2026-01-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_conversation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='time_taken_seconds',
        ),
    ]
