# Generated by Django 5.2.10 on 2026-01-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_remove_conversation_time_taken_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
